### ISSUE TITLE
Update VS test tools used by action

### ISSUE THREAD

**Issue by whsalazar** [microsoft/vstest-action#16]
The VS test tools used by this action are a fixed download from https://aka.ms/local-worker-win-x64. This needs to be updated to support as the version for VS 2019 is missing assemblies.

**Comment by brian-welsh** [comment]
agreed! the Azure DevOps equivalent is miles ahead of this. Runs with that, against the same code base succeed while this one generates failure because the version is not up to date. will add example error messages tomorrow.  
```
Data collector 'UnitTestIsolation' message: Data collector 'UnitTestIsolation' failed to provide initialization information. Error: System.TypeInitializationException: The type initializer for 'Microsoft.VisualStudio.Diagnostics.Logging.ProfilerInterop' threw an exception. ---> Microsoft.VisualStudio.Diagnostics.Common.InvariantException: Failed to load IntelliTrace Profiler binary or failed to locate functions.

Diagnostic Messages Collected when attempting to load the profiler dll
===============================================================================
Process is 64bit : True
ProfilerDLL : x64\Microsoft.IntelliTrace.Profiler.dll
Attempting to locate ProfilerDLL relative the executing assembly. Assembly: Microsoft.IntelliTrace.Core, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a. Path: D:\a\_actions\microsoft\vstest-action\v1.0.0\dist\win-x64\VsTest\v160\Common7\IDE\Extensions\TestPlatform\x64\Microsoft.IntelliTrace.Profiler.dll
Attempting to locate ProfilerDLL relative to current process. Process: datacollector. Path: D:\a\_actions\microsoft\vstest-action\v1.0.0\dist\win-x64\VsTest\v160\Common7\IDE\Extensions\TestPlatform\x64\Microsoft.IntelliTrace.Profiler.dll
Attempting to locate ProfilerDLL relative the IntelliTrace install directory: D:\a\_actions\microsoft\vstest-action\v1.0.0\dist\win-x64\VsTest\v160\Common7\IDE\CommonExtensions\Microsoft\IntelliTrace\x64\Microsoft.IntelliTrace.Profiler.dll

==============================================================================
---> System.ComponentModel.Win32Exception: The system cannot find the path specified
  --- End of inner exception stack trace ---
  at Microsoft.VisualStudio.Diagnostics.Common.Check.Throw[XT](String message, Func`1 innerEx)
  at Microsoft.VisualStudio.Diagnostics.Logging.ProfilerInterop.ThrowInvariantExceptionOnZeroPtr(IntPtr ptr, String message)
  at Microsoft.VisualStudio.Diagnostics.Logging.ProfilerInterop.InitInterop()
  at Microsoft.VisualStudio.Diagnostics.Logging.ProfilerInterop..cctor()
  --- End of inner exception stack trace ---
  at Microsoft.VisualStudio.Diagnostics.Logging.ProfilerInterop.get_InteropInterface()
  at Microsoft.VisualStudio.Diagnostics.Logging.LoggingConfig.Publish()
  at Microsoft.VisualStudio.TraceCollector.CommonDataCollector.InitiateCollection()
  at Microsoft.VisualStudio.TraceCollector.CommonDataCollector.GetEnvironmentVariables()
  at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectorInformation.SetTestExecutionEnvironmentVariables()
  at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectionManager.GetEnvironmentVariables(Boolean& unloadedAnyCollector).

```
